//////////// THIS FILE MUST BE CREATED BY EXECUTING WriteAttributeDefinitionFile ////////////
//////////// DO NOT MODIFY THIS FILE MANUALLY ///////////////////////////////////////////////

#ifndef __NOMAD_4_6_RUNATTRIBUTESDEFINITIONQUADMODEL__
#define __NOMAD_4_6_RUNATTRIBUTESDEFINITIONQUADMODEL__

_definition = {
{ "QUAD_MODEL_SEARCH",  "bool",  "true",  " Quad model search ",  " \n  \n . MADS model search, using Bastien Talgorn's Sgtelib with quad models \n  \n . Argument: one boolean ('yes' or 'no') \n  \n . Disabled for more than 50 variables \n  \n . Example: QUAD_MODEL_SEARCH yes \n  \n . Default: true\n\n",  "  basic mads quad model search model_search  "  , "true" , "true" , "true" },
{ "QUAD_MODEL_SEARCH_DYNAMIC_ENABLE",  "bool",  "false",  " Dynamic enabling/disabling of Quad Model search based on success ",  " \n  \n . Dynamic enabling/disabling of Quad Model search based on success. \n  \n . After a full success we rarely have another one. \n   Let's deactivate for the next iteration. \n    \n . This is a simple, yet efficient strategy. \n  \n . Can work well with QP_SEARCH_DYNAMIC_ENABLE. \n  \n . Argument: bool \n  \n . Example: QUAD_MODEL_SEARCH_DYNAMIC_ENABLE yes \n  \n . Default: false\n\n",  "  basic mads quad model search model_search dynamic  "  , "true" , "true" , "true" },
{ "QUAD_MODEL_SEARCH_SIMPLE_MADS",  "bool",  "false",  " Quad model search using a simpler version of Mads ",  " \n  \n . Enable quad model search using a simpler version of Mads \n  \n . Example: QUAD_MODEL_SEARCH_SIMPLE_MADS yes \n  \n . Default: false\n\n",  "  basic mads quad model search model_search  "  , "true" , "true" , "true" },
{ "QUAD_MODEL_AND_LH_SEARCH",  "bool",  "false",  " Quad model and LH search ",  " \n . Add points to construct a better quad model \n  \n . Not implemented. Triggers exception if enabled. \n  \n . Default: false\n\n",  "  basic mads quad model lh latin hypercube sampling search model_search  "  , "true" , "true" , "true" },
{ "QUAD_MODEL_SLD_SEARCH",  "bool",  "false",  " Quad model (SLD) search ",  " \n  \n . MADS model search, using Sébastien Le Digabel quad models \n  \n . Argument: one boolean ('yes' or 'no') \n  \n . Disabled for more than 50 variables \n  \n . Example: QUAD_MODEL_SLD_SEARCH yes \n  \n . Default: false\n\n",  "  basic mads quad model search model_search  "  , "true" , "true" , "true" },
{ "QUAD_MODEL_SEARCH_BOUND_REDUCTION_FACTOR",  "NOMAD::Double",  "1",  " Scale the bounds for the quad model search  ",  " \n  \n . The quad model is built on evaluation points around a frame center. This \n defines min and max bounds, from which we define a model center. The model \n search is limited to tighter (can be wider with the parameter set to less than 1) \n bounds by reducing the distance of the optimization bounds to the model center. \n We use a reduction factor for that. If the reduction factor equals one, the min \n and max bounds are used as optimization bounds for the search. The greater the \n reduction factor, the tighter the bounds. \n  \n . Argument: one Double greater than 0 \n  \n . Example: QUAD_MODEL_SEARCH_BOUND_REDUCTION_FACTOR 3.0 \n  \n . Default: 1\n\n",  "  develop mads quad model search sgtelib model_search bounds  "  , "true" , "true" , "true" },
{ "QUAD_MODEL_DISPLAY",  "std::string",  "",  " Display of a model ",  " \n . Control the display of the quad model search and quad model optimization. \n   These details are only shown if DISPLAY_DEGREE is FULL (3) or more. \n  \n . Arguments: a string containing one or several of the following letters \n  \n . \"S\": General information on the model search or optimization \n  \n . \"F\": Details of the filter step \n  \n . \"O\": Details of the models optimization \n  \n . \"P\": Details of the projection \n  \n . \"U\": Details of the model update \n  \n . \"I\": Advancement of the model optimization \n  \n . \"X\": Display of all of the model evaluations \n  \n . Example: QUAD_MODEL_DISPLAY SPF # display the general information on the search \n                                        and on the filter and projection steps \n . Default: Empty string.\n\n",  "  developer advanced model quad sgtelib  "  , "false" , "false" , "true" },
{ "QUAD_MODEL_OPTIMIZATION",  "bool",  "false",  " Quad model stand alone optimization for constrained and unconstrained pbs ",  " \n  \n . Quadratic model optimization for constrained and unconstrained \n   optimization. \n    \n . LH_EVAL can be used to sample points and evaluate them before running \n   quad model optimization. \n  \n . Argument: bool \n  \n . Stand alone quadratic model optimization will deactivate any optimization \n   strategy. \n  \n . Example: QUAD_MODEL_OPTIMIZATION true \n  \n . Default: false\n\n",  "  advanced sgtelib quadratic quad optimization simplex  "  , "true" , "false" , "true" },
{ "QUAD_MODEL_OPTIMIZATION_MIN_TR_RADIUS",  "Double",  "1E-12",  " Min trust region radius for Quad model mads optim  ",  " \n  \n . Quad model standalone Mads optimization on quadratic models for constrained and \n   unconstrained problems \n    \n . Use a Model Based Trust Region algorithm to iterate. \n  \n . Minimum trust region radius is used as termination criterion. \n  \n . The parameter QUAD_MODEL_OPTIMIZATION_MIN_TR_RADIUS is 1E-12 by default \n  \n . Argument: Double \n  \n . Example: QUAD_MODEL_OPTIMIZATION_MIN_TR_RADIUS 1E-6 \n  \n . Default: 1E-12\n\n",  "  advanced sgtelib quadratic quad optimization programming qp trust region radius "  , "true" , "false" , "true" },
{ "QUAD_MODEL_SEARCH_BOX_FACTOR",  "NOMAD::Double",  "4.0",  " Quadratic model search point selection factor ",  " \n . Quadratic model search point selection factor \n  \n . This parameter is used to select points to build the quadratic model for \n   the search method \n  \n . The max, min and average of trial points coordinates are used to identify a \n   box. This box contains all trial points to sort. \n    \n . The box is enlarged by this factor. Cache evaluation points inside this box \n   are selected to build the quadratic model for search. \n  \n . Arguments: one strictly positive real \n  \n . Example: QUAD_MODEL_SEARCH_BOX_FACTOR 1.0 \n . Default: 4.0\n\n",  "  developer quadratic model search radius  "  , "true" , "true" , "true" },
{ "QUAD_MODEL_BOX_FACTOR",  "NOMAD::Double",  "4.0",  " Quadratic model points selection box factor ",  " \n  \n . This parameter is used to select points to build the quadratic model. \n  \n . The max, min and average of trial points coordinates are used to identify a \n   box. \n    \n . The box is enlarged by this factor. Cache evaluation points inside this box \n   are selected to build the quadratic model. \n  \n . Arguments: one strictly positive real \n  \n . Example: QUAD_MODEL_BOX_FACTOR 1.0 \n . Default: 4.0\n\n",  "  developer quadratic model sort search  "  , "true" , "true" , "true" },
{ "QUAD_MODEL_SEARCH_FORCE_EB",  "bool",  "false",  " Quadratic model search optimization using extreme barrier ",  " \n  \n . By default (flag=false) quadratic model search optimization problem transforms \n   all constraints into progressive barrier constraints. \n    \n . Handling constraints with the progressive barrier is more costly (time) than \n   with the extreme barrier because updating the progressive barrier is more \n   complex. \n  \n . On costly blackbox optimization problem the extra time for using the progressive \n   barrier during the quadratic model search optimization is minimal. But it can \n   be more important on simple analytical blacbox optimization problems with many \n   quad model searches. \n    \n . Forcing EB constraints for quad model search is faster but can result in less \n   successful trial points. \n    \n . Arguments: boolean \n  \n . Example: QUAD_MODEL_FORCE_EB true \n  \n . Default: false\n\n",  "  developer quadratic model search  "  , "true" , "true" , "true" },
{ "DYNAMIC_SEARCH",  "bool",  "false",  " Dynamically enable/disable active simple search methods during run  ",  " \n  \n . NOT used for now. Tests have not shown efficiency. \n    \n . Arguments: boolean \n  \n . Default: false\n\n",  "  developer quadratic model search  "  , "true" , "true" , "true" } };

#endif
