//////////// THIS FILE MUST BE CREATED BY EXECUTING WriteAttributeDefinitionFile ////////////
//////////// DO NOT MODIFY THIS FILE MANUALLY ///////////////////////////////////////////////

#ifndef __NOMAD_4_6_RUNATTRIBUTESDEFINITIONQPSOLVER__
#define __NOMAD_4_6_RUNATTRIBUTESDEFINITIONQPSOLVER__

_definition = {
{ "QP_OPTIMIZATION",  "bool",  "false",  " Quad model stand alone QP optimization for constrained and unconstrained pbs ",  " \n  \n . QP standalone optimization on quadratic models for constrained and \n   unconstrained problems \n    \n . Use a Model Based Trust Region algorithm to iterate. \n  \n . The parameter QP_OPTIMIZATION_TR_RADIUS_MIN is 1E-12 by default \n  \n . Argument: bool \n  \n . Standalone optimization will deactivate any other optimization strategy. \n  \n . Example: QP_OPTIMIZATION true \n  \n . Default: false\n\n",  "  advanced sgtelib quadratic quad optimization programming qp  "  , "true" , "false" , "true" },
{ "QP_OPTIMIZATION_MIN_TR_RADIUS",  "Double",  "1E-12",  " Min trust region radius for QP optim  ",  " \n  \n . QP standalone optimization on quadratic models for constrained and \n   unconstrained problems \n    \n . Use a Model Based Trust Region algorithm to iterate. \n  \n . Minimum trust region radius is used as termination criterion. \n  \n . The parameter QP_OPTIMIZATION_MIN_TR_RADIUS is 1E-12 by default \n  \n . Argument: Double \n  \n . Example: QP_OPTIMIZATION_MIN_TR_RADIUS 1E-6 \n  \n . Default: 1E-12\n\n",  "  advanced sgtelib quadratic quad optimization programming qp trust region radius "  , "true" , "false" , "true" },
{ "QP_SEARCH",  "bool",  "false",  " A quad model based search step for Mads using a QP solver ",  " \n  \n . A QP search step for Mads that make several trial points from the poll center \n  \n . Argument: bool \n  \n . Example: QP_SEARCH true \n  \n . Default: false\n\n",  "  advanced algorithm search quadratic quad model programming qp  "  , "true" , "true" , "true" },
{ "QP_SEARCH_DYNAMIC_ENABLE",  "bool",  "false",  " Dynamic enabling/disabling of QP search based on success ",  " \n  \n . Dynamic enabling/disabling of QP search based on success. \n  \n . After a full success we rarely have another one. \n   Let's deactivate for the next iteration. \n    \n . This is a simple, yet efficient strategy. \n  \n . Can work well with QUAD_MODEL_SEARCH_DYNAMIC_ENABLE. \n  \n . Argument: bool \n  \n . Example: QP_SEARCH_DYNAMIC_ENABLE yes \n  \n . Default: false\n\n",  "  advanced algorithm search quadratic quad model programming qp dynamic  "  , "true" , "true" , "true" },
{ "QP_SelectAlgo",  "size_t",  "0",  " Select the algorithm for QP solver ",  " \n  \n . Select the algorithm for QPSolver. \n  \n . #0: Augmented lagrangian \n  \n . #1: Interior point method \n  \n . #2: L1 penalty augmented lagrangian \n  \n . Argument: size_t \n  \n . Example: QP_SelectAlgo 0 \n  \n . Default: 0\n\n",  "  advanced algorithm search quadratic quad model programming qp  "  , "true" , "true" , "true" },
{ "QP_absoluteTol",  "NOMAD::Double",  "1e-3",  " A quad model based search step for Mads using a QP solver ",  " \n  \n . QPSolver absolute tolerance \n  \n . Argument: Double \n  \n . Example: QP_absoluteTol 1e-3 \n  \n . Default: 1e-3\n\n",  "  advanced algorithm search quadratic quad model programming qp  "  , "true" , "true" , "true" },
{ "QP_tolCond",  "NOMAD::Double",  "1e-15",  " A quad model based search step for Mads using a QP solver ",  " \n  \n . QPSolver relative tolerance w.r.t to condition number \n  \n . Argument: Double \n  \n . Example: QP_tolCond 1e-15 \n  \n . Default: 1e-15\n\n",  "  advanced algorithm search quadratic quad model programming qp  "  , "true" , "true" , "true" },
{ "QP_tolMesh",  "NOMAD::Double",  "1.0",  " A quad model based search step for Mads using a QP solver ",  " \n  \n . QPSolver relative tolerance w.r.t to mesh size \n  \n . Argument: Double \n  \n . Example: QP_tolMesh 1.0 \n  \n . Default: 1.0\n\n",  "  advanced algorithm search quadratic quad model programming qp  "  , "true" , "true" , "true" },
{ "QP_relativeTol",  "NOMAD::Double",  "1e-3",  " A quad model based search step for Mads using a QP solver ",  " \n  \n . QPSolver relative tolerance \n  \n . Argument: Double \n  \n . Example: QP_relativeTol 1e-3 \n  \n . Default: 1e-3\n\n",  "  advanced algorithm search quadratic quad model programming qp  "  , "true" , "true" , "true" },
{ "QP_verbose",  "bool",  "false",  " A quad model based search step for Mads using a QP solver ",  " \n  \n . QPSolver verbosity \n  \n . Argument: bool \n  \n . Example: verbose false \n  \n . Default: false\n\n",  "  advanced algorithm search quadratic quad model programming qp  "  , "true" , "true" , "true" },
{ "QP_verboseFull",  "bool",  "false",  " A quad model based search step for Mads using a QP solver ",  " \n  \n . QPSolver verbosity of all subiterations \n  \n . Argument: bool \n  \n . Example: QP_verboseFull false \n  \n . Default: false\n\n",  "  advanced algorithm search quadratic quad model programming qp  "  , "true" , "true" , "true" },
{ "QP_AugLag_mu0",  "NOMAD::Double",  "0.5",  " A quad model based search step for Mads using a QP solver ",  " \n  \n . QPSolver initial penalty parameter value for Augmented Lagrangian solver \n  \n . Argument: Double \n  \n . Example: QP_AugLag_mu0 0.5 \n  \n . Default: 0.5\n\n",  "  advanced algorithm search quadratic quad model programming qp  "  , "true" , "true" , "true" },
{ "QP_AugLag_eta0",  "NOMAD::Double",  "1.0",  " A quad model based search step for Mads using a QP solver ",  " \n  \n . QPSolver initial constraint tolerance value for Augmented Lagrangian solver \n  \n . Argument: Double \n  \n . Example: QP_AugLag_eta0 1.0 \n  \n . Default: 1.0\n\n",  "  advanced algorithm search quadratic quad model programming qp  "  , "true" , "true" , "true" },
{ "QP_AugLag_omega0",  "NOMAD::Double",  "1.0",  " A quad model based search step for Mads using a QP solver ",  " \n  \n . QPSolver initial subproblem's tolerance value for Augmented Lagrangian solver \n  \n . Argument: Double \n  \n . Example: QP_AugLag_omega0 1.0 \n  \n . Default: 1.0\n\n",  "  advanced algorithm search quadratic quad model programming qp  "  , "true" , "true" , "true" },
{ "QP_AugLag_maxIterInner",  "size_t",  "50",  " QPSolver inner iteration limit for the subproblem ",  " \n  \n . QPSolver augmented lagrangian inner iteration limit for the subproblem \n  \n . Argument: size_t \n  \n . Example: QP_AugLag_maxIterInner 10 \n  \n . Default: 50\n\n",  "  advanced algorithm search quadratic quad model programming qp  "  , "true" , "true" , "true" },
{ "QP_AugLag_tolDistDXInner",  "NOMAD::Double",  "1e-15",  " A quad model based search step for Mads using a QP solver ",  " \n  \n . QPSolver smallest progress accepted in the subproblem \n  \n . Argument: Double \n  \n . Example: QP_AugLag_tolDistDXInner 1e-15 \n  \n . Default: 1e-15\n\n",  "  advanced algorithm search quadratic quad model programming qp  "  , "true" , "true" , "true" },
{ "QP_SEARCH_MODEL_BOX_SIZE_LIMIT",  "NOMAD::Double",  "0",  " QP solver generates trial points if bounds box size is above limit  ",  " \n  \n . QP solver generates trial points if bounds box size is above limit. \n  \n . Default: 0, always goes into trial point generation step. \n  \n . Default: 0\n\n",  "  advanced algorithm search quadratic quad model programming qp box  "  , "true" , "true" , "true" } };

#endif
