task:
  matrix:
    - name: FreeBSD -- gcc | g++
      freebsd_instance:
        image: freebsd-14-2-release-amd64-ufs
      env:
        cc: gcc13
        cxx: g++13
    - name: FreeBSD -- clang | clang++
      freebsd_instance:
        image: freebsd-14-0-release-amd64-ufs
      env:
        cc: clang
        cxx: clang++
    - name: MacOS M1 -- gcc | g++
      macos_instance:
        image: ghcr.io/cirruslabs/macos-runner:sonoma
      env:
        cc: gcc-15
        cxx: g++-15
    - name: MacOS M1 -- clang | clang++
      macos_instance:
        image: ghcr.io/cirruslabs/macos-runner:sonoma
      env:
        cc: clang
        cxx: clang++
  dependencies_script: |
    echo $(uname)
    if [ "$(uname)" = "FreeBSD" ]; then
      pkg install -y cmake bash gcc13
    else
      brew install cmake gcc@12
    fi
  configure_script: |
    mkdir instdir
    mkdir build
    cd build
    cmake \
      -DCMAKE_C_COMPILER=$cc \
      -DCMAKE_CXX_COMPILER=$cxx \
      -DTEST_OPENMP=OFF \
      -DBUILD_INTERFACE_C=ON \
      -DCMAKE_INSTALL_PREFIX=../instdir \
      ..
  build_script: |
    cmake --build build --parallel 8 --config Release
  install_script: |
    cmake --install build --config Release
  test_script: |
    export PATH=`pwd`/build/bin:$PATH
    echo $PATH
    if [ "$(uname)" = "FreeBSD" ]; then
      ln -s /usr/local/bin/bash /bin/bash
    fi
    cd build
    ctest -C Release --parallel 8
