freebsd_instance:
  image: freebsd-13-1-release-amd64
task:
  name: FreeBSD
  dependencies_script: |
    pkg install -y cmake bash
  configure_script: |
    mkdir instdir
    mkdir build
    cd build
    cmake \
      -DTEST_OPENMP=OFF \
      -DBUILD_INTERFACE_C=ON \
      -DBUILD_TESTS=ON \
      -DCMAKE_INSTALL_PREFIX=../instdir \
      ..
  build_script: |
    cmake --build build --parallel 8 --config Release
  install_script: |
    cmake --install build --config Release
  test_script: |
    export PATH=`pwd`/build/bin:$PATH
    echo $PATH
    ln -s /usr/local/bin/bash /bin/bash
    cd build
    ctest -C Release --parallel 8

macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest
task:
  name: MacOS M1
  dependencies_script: |
    /opt/homebrew/bin/brew install cmake
  configure_script: |
    mkdir instdir
    mkdir build
    cd build
    cmake \
      -DTEST_OPENMP=OFF \
      -DBUILD_INTERFACE_C=ON \
      -DBUILD_TESTS=ON \
      -DCMAKE_INSTALL_PREFIX=../instdir \
      ..
  build_script: |
    cmake --build build --parallel 8 --config Release
  install_script: |
    cmake --install build --config Release
  test_script: |
    export PATH=`pwd`/build/bin:$PATH
    echo $PATH
    cd build
    ctest -C Release --parallel 8
