language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env: THREADING="openmp"

    # clang
    - os: osx
      osx_image: xcode11.3
      compiler: clang

    # gcc
    - os: osx
      osx_image: xcode11.3
      compiler: gcc
      before_install:
        - rm -rf /usr/local/include/c++
        - export CC=gcc && export CXX=g++
        - THREADING="openmp"

env:
  - OMP_NUM_THREADS=4

before_script:
  - mkdir build
  - cd build

script:
  # installation
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake -DNOMAD_WITH_OPENMP=OFF ..
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake ..
    fi
  - make -j2 VERBOSE=1
  # test simple c++ examples and c examples
  - cd examples && ./basic_lib_example1 && ./basic_lib_example2 && ./basic_lib_example3 && ./exampleForCustomHComputation && ./example1_c_api && ./example2_c_api
  - make install
